apiVersion: v1
kind: Pod
metadata:
  name: secure-pod-1
  namespace: audit-zone
spec:
  containers:
  - name: nginx
    image: nginx
    securityContext:
      privileged: false
      allowPrivilegeEscalation: false
      capabilities:
        drop:
        - ALL
      readOnlyRootFilesystem: true
      runAsNonRoot: true
      runAsUser: 1000