apiVersion: constraints.gatekeeper.sh/v1beta1
kind: HostPathPods
metadata:
  name: hostpath-pods
spec:
  match:
    kinds:
    - apiGroups: [""]
      kinds: ["Pod"]
    namespaces:
    - "audit-zone"