apiVersion: constraints.gatekeeper.sh/v1beta1
kind: RootUserPods
metadata:
  name: rootuser-pods
spec:
  match:
    kinds:
    - apiGroups: [""]
      kinds: ["Pod"]
    namespaces:
    - "audit-zone"