apiVersion: v1
kind: Pod
metadata:
  name: secure-pod-2
  namespace: audit-zone
spec:
  securityContext:
    seccompProfile:
      type: RuntimeDefault
  containers:
  - name: nginx
    image: nginx
    securityContext:
      allowPrivilegeEscalation: false
      capabilities:
        drop:
        - ALL
      runAsNonRoot: true
      runAsUser: 101
    volumeMounts:
    - mountPath: /var/cache/nginx
      name: cache
    - mountPath: /var/run
      name: run
    - mountPath: /data
      name: empty-volume
  volumes:
  - name: cache
    emptyDir: {}
  - name: run
    emptyDir: {}
  - name: empty-volume
    emptyDir: {}